<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260721105249 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'create Deals table';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE deal (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, amount NUMERIC(10, 2) NOT NULL, status VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, client_id INT NOT NULL, created_by_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_E3FEC11619EB6921 ON deal (client_id)');
        $this->addSql('CREATE INDEX IDX_E3FEC116B03A8386 ON deal (created_by_id)');
        $this->addSql('ALTER TABLE deal ADD CONSTRAINT FK_E3FEC11619EB6921 FOREIGN KEY (client_id) REFERENCES client (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE deal ADD CONSTRAINT FK_E3FEC116B03A8386 FOREIGN KEY (created_by_id) REFERENCES users (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE deal DROP CONSTRAINT FK_E3FEC11619EB6921');
        $this->addSql('ALTER TABLE deal DROP CONSTRAINT FK_E3FEC116B03A8386');
        $this->addSql('DROP TABLE deal');
    }
}
